ws.db: fix overconstrained namespace tables
There are currently a few conflicting requirements:
- namespace_name must only have one row per ID (deduplicated).
- namespace_name should prefer the alias name when available.
- namespace_starname and namespace_canonical, expect a (ID, name) foreign key in namespace_name.

Currently, in a case where we have a starname (6, "File") but an alias "Image",
then GrabberNamespaces will elect to add a (6, "Image") entry to namespace_name.
This violates the fkey constraint, causing an error:

sqlalchemy.exc.IntegrityError: (psycopg.errors.ForeignKeyViolation) insert or update on table "namespace_canonical" violates foreign key constraint "namespace_canonical_nsc_id_nsc_name_fkey"
DETAIL:  Key (nsc_id, nsc_name)=(6, File) is not present in table "namespace_name".
[SQL: INSERT INTO namespace_canonical (nsc_id, nsc_name) VALUES (%(nsc_id)s::INTEGER, %(nsc_name)s::VARCHAR) ON CONFLICT (nsc_id) DO UPDATE SET nsc_name = excluded.nsc_name]
[parameters: [{'nsc_id': -2, 'nsc_name': 'Media'}, {'nsc_id': -1, 'nsc_name': 'Special'}, {'nsc_id': 1, 'nsc_name': 'Talk'}, {'nsc_id': 2, 'nsc_name': 'User'}, {'nsc_id': 3, 'nsc_name': 'User talk'}, {'nsc_id': 4, 'nsc_name': 'Project'}, {'nsc_id': 5, 'nsc_name': 'Project talk'}, {'nsc_id': 6, 'nsc_name': 'File'}  ... displaying 10 of 19 total bound parameter sets ...  {'nsc_id': 3000, 'nsc_name': 'DeveloperWiki'}, {'nsc_id': 3001, 'nsc_name': 'DeveloperWiki talk'}]]

Even if the alias requirement were eliminated, this constraint still causes
issues if the starname and canonical name differ.

This commit modifies the schema to loosen the constraint. Now, only the ID is
required to exist in `namespace_name` (and in `namespace`, as before).

The migration has been edited to run the operations in the correct order, as
well as give a name to the constraint. It has been tested in both directions,
though the downgrade will *not* work if there is data violating the (ID, name)
constraint.