ws.db.grabbers: fix namespace_names fkey violation
namespace_starname and namespace_canonical are (id, name) tuples which use
foreign keys from namespace_names, so we need to insert the namespace_names
row first. Fixes the link-checker.py error:

sqlalchemy.exc.IntegrityError: (psycopg.errors.ForeignKeyViolation) insert or update on table "namespace_starname" violates foreign key constraint "namespace_starname_nss_id_nss_name_fkey"
DETAIL:  Key (nss_id, nss_name)=(-2, Media) is not present in table "namespace_name".
[SQL: INSERT INTO namespace_starname (nss_id, nss_name) VALUES (%(nss_id)s::INTEGER, %(nss_name)s::VARCHAR) ON CONFLICT (nss_id) DO UPDATE SET nss_name = excluded.nss_name]
[parameters: [{'nss_id': -2, 'nss_name': 'Media'}, ...  {'nss_id': 3000, 'nss_name': 'DeveloperWiki'}, {'nss_id': 3001, 'nss_name': 'DeveloperWiki talk'}]]